./install-owns.sh
./install-upgrade.sh
./install-packages.sh
./install-mate-1.6.sh
./install-pbzip-pigz-default.sh
./install-zsh-default.sh
./install-git-color.sh
./install-configs.sh
./install-apparmor-enforce.sh
./remove-unnecessary-packages.sh
